# Generated by Django 3.0.7 on 2020-06-16 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='createDate',
            new_name='created_at',
        ),
    ]
