# Generated by Django 3.0.7 on 2020-06-25 13:39

import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'Пользователь с таким именем уже существует'}, max_length=150, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9_\\-\\.]+$', 'Имя пользователя должно состоять из английских букв, цифр и -,_,.'), django.contrib.auth.validators.ASCIIUsernameValidator]),
        ),
    ]
